services:
  web:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - redis
  
  redis:
    image: redis
    hostname: my-redis
    volumes: 
      - redis-data:/data
  
volumes:
  redis-data:

